version: '3'
services:

  db:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "1235:1235"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always