version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_USER: test_username
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"